from turtle import*

screen =  Screen()
screen.bgcolor("light pink")
screen.title("Write your name")
screen.setup(width=1000, height = 400)
yertle = Turtle("turtle")
yertle.color("white")
yertle.width(8)
yertle.setheading(0)
yertle.speed(0)
# east = 0, north = 90, west = 180, south =270

yertle.penup()
yertle.goto(-300, 100)
yertle.pendown()
yertle.setheading(270)
yertle.forward(200)
yertle.penup()
yertle.sety(0)
yertle.setheading(0)
yertle.pendown()
yertle.forward(100)
yertle.penup()
yertle.goto(-200,100)
yertle.setheading(270)
yertle.pendown()
yertle.forward(200)
yertle.penup()
yertle.setheading(0)
yertle.forward(100)

yertle.color("blue")
yertle.goto(-130,-100)
yertle.setheading(0)
yertle.pendown()
yertle.circle(60,360)
yertle.penup()
yertle.goto(-70,40)
yertle.setheading(270)
yertle.pendown()
yertle.forward(145)
yertle.penup()

yertle.color("yellow")
yertle.goto(-20,40)
yertle.setheading(0)
yertle.pendown()
yertle.forward(100)
yertle.goto(-20,-100)
yertle.forward(100)

yertle.color("green")
yertle.penup()
yertle.goto(100,-25)
yertle.pendown()
yertle.forward(140)
yertle.setheading(90)
yertle.circle(70,255)
yertle.setheading(0)
yertle.forward(75)

yertle.color("teal")
yertle.penup()
yertle.goto(300,40)
yertle.setheading(270)
yertle.pendown()
yertle.forward(150)

yertle.hideturtle()


#yertle.circle(100,180)
screen.exitonclick()