from turtle import*

screen =  Screen()
screen.bgcolor("light pink")
screen.title("Write your name")
screen.setup(width=1000, height = 400)
yertle = Turtle("turtle")
yertle.color("white")
yertle.width(8)
yertle.setheading(0)
# east = 0, north = 90, west = 180, south =270
yertle.penup()
yertle.goto(-300, 100)
yertle.pendown()
yertle.setheading(270)
yertle.forward(200)
yertle.penup()
yertle.sety(0)
yertle.setheading(0)
yertle.pendown()
yertle.forward(100)
yertle.penup()
yertle.goto(-200,100)
yertle.setheading(270)
yertle.pendown()
yertle.forward(200)
yertle.penup()
yertle.setheading(0)
yertle.forward(100)
yertle.goto(-100,-100)
yertle.setheading(0)
yertle.pendown()
yertle.circle(80,-180)
yertle.penup()
yertle.sety(100)
yertle.setheading(270)
#yertle.circle(100,180)
screen.exitonclick()